[ids]
*

[main]
# Convierte Alt Derecho en el modificador de la capa 'rcmd'
rightalt = layer(rcmd)

[rcmd]
# Mapea letras a-z a Ctrl+Super+Shift+<letra> para ser capturadas por el DE / window manager
a = C-M-S-a
b = C-M-S-b
c = C-M-S-c
d = C-M-S-d
e = C-M-S-e
f = C-M-S-f
g = C-M-S-g
h = C-M-S-h
i = C-M-S-i
j = C-M-S-j
k = C-M-S-k
l = C-M-S-l
m = C-M-S-m
n = C-M-S-n
o = C-M-S-o
p = C-M-S-p
q = C-M-S-q
r = C-M-S-r
s = C-M-S-s
t = C-M-S-t
u = C-M-S-u
v = C-M-S-v
w = C-M-S-w
x = C-M-S-x
y = C-M-S-y
z = C-M-S-z

# Números opcionales
0 = C-M-S-0
1 = C-M-S-1
2 = C-M-S-2
3 = C-M-S-3
4 = C-M-S-4
5 = C-M-S-5
6 = C-M-S-6
7 = C-M-S-7
8 = C-M-S-8
9 = C-M-S-9
